#!/bin/bash
# use this file to commit and push across all repositories. This can be very dangerous!

while getopts m:e option
do
	case "${option}"
	in
	m) MESSAGE=${OPTARG};;
	e) MESSAGE=${OPTARG};;
	esac
done

cd ..
FILES=*
echo '>>> Start pulling all vistorian repos'
for file in $FILES
do
	if [[ -d "$file" ]]; then
		echo '----------------'
		echo '>> GIT PULL in dir: ' $file 
		cd $file
		git add --all
		git commit -m "$MESSAGE"
		git push
		echo '<< COMMIT DONE'
		cd .. 
   	fi
done

echo '<<<<<< End pulling all vistorian repos'
# return to this folder
cd bashscripts

./local