#!/bin/bash

cd ..
FILES=*

echo '>>>>>> START PREPARE GLOBAL DEVELOPMENT >>>>>>>'
for file in $FILES
do
	echo 'next directory: ' $file
	if [[ -d "$file" ]]; then
		echo '-------------------'
		echo '>> LINK TO NPM REPOS FILES in dir' $file 
	    cd $file
	 	sed -i '' 's/"vistorian-core": "file:..\/vistorian-core"/"vistorian-core": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-nodelink": "file:..\/vistorian-nodelink"/"vistorian-nodelink": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-matrix": "file:..\/vistorian-matrix"/"vistorian-matrix": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-map": "file:..\/vistorian-map"/"vistorian-map": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-dynamicego": "file:..\/vistorian-dynamicego"/"vistorian-dynamicego": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-bookmarkbrowser": "file:..\/vistorian-bookmarkbrowser"/"vistorian-bookmarkbrowser": "latest"/g' package.json
	 	sed -i '' 's/"vistorian-web": "file:..\/vistorian-web"/"vistorian-web": "latest"/g' package.json
	  	echo '<< DONE ' $file
   	 	cd ..  
   	fi
done
echo '<<<<<< END PREPARE GLOBAL DEVELOPMENT <<<<<<<<<'

# return to this folder
cd bashscripts